
GET http://localhost:4000/posts
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS29maSIsImlhdCI6MTYzMDAyMjI3Mn0.FkiBIUSaJz37JYPwPjaydfSlGK_WLxRsTxEQLBVsEI4

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Kofi"
    

}


#  "username":"Kayla",